server:
  port: 8080
logging:
  level:
    "org.aigor.r2dbc.demo": "DEBUG"
    "org.springframework.jdbc.core.JdbcTemplate": "DEBUG"
    "org.springframework.data.r2dbc": "DEBUG"

# Database configurations (Postgres)

spring:
  datasource:
      url: "jdbc:postgresql://localhost:5432/application"
      username: "postgres"
      password: "postgres"
      driver-class-name: "org.postgresql.Driver"

worker:
  jdbc:
    size: 4
  r2dbc:
    size: 4
